import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FileText, Calendar } from 'lucide-react';
import { resumeService } from '../services/resumeService';
import { analysisService } from '../services/analysisService';

import LoadingState from '../components/analysis/LoadingState';
import ErrorState from '../components/analysis/ErrorState';
import OverallScoreCard from '../components/analysis/OverallScoreCard';
import ATSCard from '../components/analysis/ATSCard';
import ResumeSummary from '../components/analysis/ResumeSummary';
import StrengthsCard from '../components/analysis/StrengthsCard';
import WeaknessesCard from '../components/analysis/WeaknessesCard';
import SuggestionsList from '../components/analysis/SuggestionsList';
import SkillsAnalysis from '../components/analysis/SkillsAnalysis';
import InterviewReadiness from '../components/analysis/InterviewReadiness';

export default function AnalysisPage() {
  const { id } = useParams();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError(null);
        if (id) {
          const [parsedData, analysisData] = await Promise.all([
            resumeService.getParsedResume(id),
            analysisService.getAnalysis(id)
          ]);
          
          setData({
            parsed: parsedData,
            analysis: analysisData
          });
        } else {
          throw new Error("Invalid analysis ID");
        }
      } catch (err) {
        setError(err.message || 'Failed to fetch analysis data');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [id]);

  if (loading) return <LoadingState />;
  if (error) return <ErrorState error={error} />;
  if (!data) return null;

  const { parsed, analysis } = data;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-7xl mx-auto flex flex-col gap-8 pb-12"
    >
      {/* Page Header */}
      <div className="flex flex-col gap-2 mb-4">
        <h1 className="text-3xl md:text-4xl font-bold text-white tracking-tight">
          AI Resume Analysis
        </h1>
        <p className="text-gray-400 text-lg">
          Comprehensive feedback and scoring generated by Gemini AI.
        </p>

        <div className="flex flex-wrap items-center gap-4 mt-4 text-sm font-medium text-gray-500">
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/5 border border-white/5">
            <FileText size={14} className="text-accent-blue" />
            <span className="text-gray-300">Resume #{parsed.resume_id || id}</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Calendar size={14} />
            {new Date(analysis.created_at).toLocaleDateString()}
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1">
          <OverallScoreCard score={analysis.overall_score} />
        </div>
        <div className="lg:col-span-1">
          <ATSCard score={analysis.ats_score} />
        </div>
        <div className="lg:col-span-1">
          <div className="glass-card p-6 h-full flex flex-col justify-center gap-2 text-center">
            <h3 className="text-lg font-semibold text-gray-300">Experience Level</h3>
            <p className="text-3xl font-bold text-white">{analysis.experience_level}</p>
          </div>
        </div>
      </div>
      
      <ResumeSummary summary={analysis.summary} />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <StrengthsCard strengths={analysis.strengths} />
        <WeaknessesCard weaknesses={analysis.weaknesses} />
      </div>

      <SkillsAnalysis 
        detected={analysis.technical_skills.concat(analysis.soft_skills)} 
        missing={analysis.missing_keywords} 
      />

      <SuggestionsList 
        suggestions={analysis.improvements.map(imp => ({
          priority: 'Medium',
          category: 'Action Item',
          description: imp
        }))} 
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <InterviewReadiness 
          readiness={Math.round(analysis.overall_score)} 
          confidence={analysis.overall_score > 80 ? 'High' : analysis.overall_score > 60 ? 'Moderate' : 'Low'} 
        />
        <div className="glass-card p-6 h-full">
          <h3 className="text-xl font-bold text-white mb-3">Interview Questions</h3>
          <ul className="list-disc list-inside text-gray-300 space-y-2">
            {analysis.interview_questions.map((q, idx) => (
              <li key={idx} className="text-sm">{q}</li>
            ))}
          </ul>
        </div>
      </div>

      <div className="glass-card p-6 border-l-4 border-l-accent-purple bg-accent-purple/5">
        <h3 className="text-xl font-bold text-white mb-3">Recommended Roles</h3>
        <div className="flex flex-wrap gap-2">
          {analysis.recommended_roles.map((role, idx) => (
            <span key={idx} className="bg-accent-purple/20 text-accent-purple px-4 py-2 rounded-lg font-medium">
              {role}
            </span>
          ))}
        </div>
        <h3 className="text-xl font-bold text-white mt-6 mb-3">Career Advice</h3>
        <ul className="list-disc list-inside text-gray-300 space-y-2">
          {analysis.career_advice.map((advice, idx) => (
            <li key={idx}>{advice}</li>
          ))}
        </ul>
      </div>

    </motion.div>
  );
}
